# Generated by Django 2.2.3 on 2019-07-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webapp", "0002_song_song")]

    operations = [
        migrations.AlterField(
            model_name="song", name="song", field=models.FileField(upload_to="media/")
        )
    ]
