# Generated by Django 2.2.3 on 2019-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190814_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
