# Generated by Django 2.2.3 on 2019-08-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.CharField(default='key', max_length=30, unique=True),
        ),
    ]
