# Generated by Django 2.2.3 on 2019-08-19 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190818_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ManyToManyField(related_name='user_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
