# Generated by Django 2.2.3 on 2019-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20190819_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='picture',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
