# Generated by Django 2.2.3 on 2019-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_song_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='picture',
            field=models.CharField(default='no picture', max_length=1000, null=True),
        ),
    ]
