# Generated by Django 2.2.3 on 2019-08-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20190821_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.CharField(default='No picture', max_length=255),
        ),
    ]
